{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "nodemon",
    "build": "tsc && tsc-alias",
    "start": "node dist/server.js"
  },
  "engines": {
    "node": "22.17.0"
  },
  "keywords": []
}
